origin    : pkg-config
name      : ruby-pkg-config
version   : 1.3.1
category  : ruby
summary   : A pkg-config implementation for Ruby
maintainer: devel@slitaz.org
license   : LGPL2.1
home      : https://rubygems.org/gems/<o>
target    : noarch
repology  : ruby:pkg-config

src:
- url:  https://rubygems.org/downloads/<o>-<v>.gem

bdeps: ruby-dev

make:
  type: ruby

pkgs:
- pkg : main
  copy: '@ruby'
  deps: ruby
