name      : libcompizconfig
version   : 0.8.14
category  : x-window
summary   : Compiz configuration library
maintainer: devel@slitaz.org
license   : GPL2
home      : https://gitlab.com/compiz/libcompizconfig

src:
- url:  https://gitlab.com/compiz/<n>/-/archive/v<v>/<n>-v<v>.tar.bz2

bdeps: [automake, libtool, libx11-dev, compiz-dev, protobuf-dev, libxslt-dev,
        mesa-dev]

prepare: |
  mkdir -p m4
  NOCONFIGURE=1 ./autogen.sh

make:
  type: gnu

pkgs:
- pkg : main
  deps: [libxml2, libx11]
  provide: compiz-libcompizconfig
  conf: /etc/compizconfig/config
  tags: compiz

- pkg : dev
  deps: [std, compiz-dev]
